### ISSUE TITLE
Chat widget doesn't load on item pages that are "full display"

### ISSUE THREAD

**Issue by AmericanIris** [NYULibraries/primo-explore-nyu#33]
@barnabyalter 

## The libraryh3lp widget does not appear on a "full display" page for an item. 
Such as you get via a [permalink](http://bobcat.library.nyu.edu/primo-explore/fulldisplay?docid=nyu_aleph004176503&context=L&vid=NYU&search_scope=all&isFrbr=true&tab=all&lang=en_US)
May occur in all views.

- [**Screengrab**](https://nyu.box.com/s/u2xm1cpb9fo9wue14bdtwatyc1nyqjrf)
**Screenshot:**
![primo-explore-nyu_bug_libraryh3lp_screenshot](https://user-images.githubusercontent.com/13155169/47028610-b2ebbb80-d137-11e8-93b3-d281a57a16ad.png)

**Comment by barnabyalter** [comment]
@etgrieco please take a look at this when you have a chance. i'm pretty sure i fixed this in some iteration and it disappeared in the next

**Comment by etgrieco** [comment]
@barnabyalter Will do. Doesn't even seem to be showing up on the DOM, so I wonder if we'll have to 
use another `prm...after` component. I'll work on this.

**Comment by etgrieco** [comment]
@AmericanIris @barnabyalter

So, because the `full-view` and the `explore` view use completely different wrapping elements, there isn't a consistent component we can inject into between the two views. 

One solution would be to simply add:
```
angular.module('viewCustom').component(
    'prmFullViewPageAfter', {
    bindings: {
      parentCtrl: '<'
    },
    controller: 'libraryh3lpWidgetController',
    template: template
  });
```

But the drawback of this strategy is that there would be two instances of the chat running; the `full-display` chat would not persist across the single page application, since the `explore` view would take over when `full-display` basically gets complete removed from the DOM.

Here is a screencast of the behavior with that solution in place: https://nyu.box.com/s/qn2ti2o0jw5lm4y2vv7onlpj2u4f771k

@AmericanIris I am looking for your opinion on this from a UX standpoint -- basically a persistent chat between `full-display` and `explore` views is technically infeasible. I guess we have a few choices:
1) Leave the behavior as is: you must be in the `explore` view to chat
2) Allow for the second chat, but risk that users will 'kill' the chat when they navigate away from the page.
3) (a bit convoluted): Display a `libraryh3lp` component on the `full-display`, but instead of opening the chat, what it will do is trigger the user to go to the `primo-explore` interface, then automatically open the chat window so that the user can freely navigate bobcat while chatting.

**Comment by barnabyalter** [comment]
@etgrieco thanks for exploring this. i actually don't think it's a valid use case that a user would have an open chat session from brief results to full display because the overlay view is the only "full view" seen when coming through search results. the only way to get to the "full view" referenced in this issue is by going directly to the permalink or, when on the overlay, reloading the page. the chat doesn't persist when reloading a page anyway or navigating away from the current page.

**Comment by barnabyalter** [comment]
@etgrieco that is to say I don't see any issue with your proposed solution except that it is something we'd want to implement at the module level: https://github.com/NYULibraries/primo-explore-libraryh3lp-widget/blob/master/src/js/libraryh3lp-widget.module.js#L32

**Comment by etgrieco** [comment]
@barnabyalter As per our conversation, we'll use `prmSilentLoginAfter` -- seems to work perfectly across the views. Thanks for finding that.

https://nyu.box.com/s/kcppg5rvzmw60syqnps6xatc3e60erji

Works as expected, I'll implement this at the module level. Luckily no major version change is necessary, it is perfectly compatible with the default CSS.

**Comment by etgrieco** [comment]
@AmericanIris @barnabyalter The fix/enhancement has been put on bobcatdev.

Example:

http://bobcatdev.library.nyu.edu/primo-explore/fulldisplay?docid=nyu_aleph000455174&context=L&vid=NYU&lang=en_US&search_scope=all&adaptor=Local%20Search%20Engine&tab=all&query=any,contains,monk&sortby=rank&offset=0

@AmericanIris send a thumbs-up and I'll also bring over to dev and NYUAD

**Comment by barnabyalter** [comment]
@etgrieco Looks great!

**Comment by etgrieco** [comment]
@AmericanIris @barnabyalter going ahead and merging/putting that on production now.
